# Generated by Django 2.2.5 on 2019-11-12 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rover_base_station', '0002_gps'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccGyro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('accX', models.FloatField()),
                ('accY', models.FloatField()),
                ('accZ', models.FloatField()),
                ('gyroX', models.FloatField()),
                ('gyroY', models.FloatField()),
                ('gyroZ', models.FloatField()),
            ],
        ),
    ]
