# Generated by Django 2.2.5 on 2020-01-05 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rover_base_station', '0005_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='img',
            field=models.FileField(upload_to='images'),
        ),
    ]
