# Generated by Django 2.2.7 on 2020-01-25 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rover_base_station', '0008_auto_20200105_1333'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rover_Base_Station',
        ),
    ]
