# Generated by Django 2.2.7 on 2020-02-08 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rover_base_station', '0009_delete_rover_base_station'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lidar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('data', models.CharField(max_length=4096)),
            ],
        ),
    ]
