# Generated by Django 2.2.7 on 2020-02-08 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rover_base_station', '0010_lidar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lidar',
            name='data',
        ),
        migrations.AddField(
            model_name='lidar',
            name='img',
            field=models.TextField(blank=True),
        ),
    ]
